name: DRIP-seq_STAR
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - cutadapt==5.2
  - bowtie2=2.5.4
  - samtools=1.6
  - bedtools=2.31.1
  # add any other tools your processes use